version: '3'

services:
  api:
    build:
      context: .
      dockerfile: flask.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api:/movie_name/api

  client:
    build:
      context: .
      dockerfile: client/vite.dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/movie_name/client
      - /movie_name/client/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true