name: Python Style Check

on:
  pull_request:
    paths:
      - '**.py'

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.py

      - name: Run pycodestyle on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          pip install pycodestyle
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            pycodestyle "$file"
          done
